# -*- coding: utf-8 -*-
"""Methylation Journal ALL code for BNNs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIBQ9Ovv04AZWY1QB7BiWGiU8FuCBSj7
"""

#HMS VS WED

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf
from imblearn.over_sampling import SMOTE

# Load Dataset
file_path = "/content/HMS VS WED(ch)transposed.csv"
data = pd.read_csv(file_path, low_memory=False)

# Display basic dataset info
print(data.head())
print(data.info())

# Ensure all columns except the target are numeric
# Drop non-numeric columns like 'Position' if necessary
data = data.select_dtypes(include=[np.number])

# Separate features and target
target_column = "Classification"  # Replace with the correct target column
if target_column not in data.columns:
    print("Ensure the target column name matches your dataset.")
    exit()

X = data.drop(columns=[target_column])
Y = data[target_column].astype(int)  # Convert target to integer type

print(f"Class distribution: {np.bincount(Y)}")

# Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle Class Imbalance
smote = SMOTE(random_state=42)
X_train, Y_train = smote.fit_resample(X_train, Y_train)
print(f"Class distribution after SMOTE: {np.bincount(Y_train)}")

# Build Model
inputs = tf.keras.Input(shape=(X_train.shape[1],))
x = tf.keras.layers.Dense(units=128, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(units=1, activation='sigmoid')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Compile Model
class_weights = {0: 1.0, 1: 1.0}  # Adjust these weights if class imbalance persists
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Train Model
history = model.fit(
    X_train, Y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    class_weight=class_weights,
    verbose=1
)

# Evaluate Model
loss, accuracy, precision, recall = model.evaluate(X_test, Y_test)
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype('int32')

# Confusion Matrix and Classification Report
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred_binary))
print("\nClassification Report:")
print(classification_report(Y_test, y_pred_binary))

# Compute ROC-AUC
roc_auc = roc_auc_score(Y_test, y_pred)
print(f"ROC AUC Score: {roc_auc:.4f}")

"""# **HMS VS WED WITHOUT XY**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf
from imblearn.over_sampling import SMOTE

# Load Dataset
file_path = "/content/HMS VS WED(wxy)transposed.csv"
data = pd.read_csv(file_path, low_memory=False)

# Display basic dataset info
print(data.head())
print(data.info())

# Ensure all columns except the target are numeric
# Drop non-numeric columns like 'Position' if necessary
data = data.select_dtypes(include=[np.number])

# Separate features and target
target_column = "Classification"  # Replace with the correct target column
if target_column not in data.columns:
    print("Ensure the target column name matches your dataset.")
    exit()

X = data.drop(columns=[target_column])
Y = data[target_column].astype(int)  # Convert target to integer type

print(f"Class distribution: {np.bincount(Y)}")

# Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle Class Imbalance
smote = SMOTE(random_state=42)
X_train, Y_train = smote.fit_resample(X_train, Y_train)
print(f"Class distribution after SMOTE: {np.bincount(Y_train)}")

# Build Model
inputs = tf.keras.Input(shape=(X_train.shape[1],))
x = tf.keras.layers.Dense(units=128, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(units=1, activation='sigmoid')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Compile Model
class_weights = {0: 1.0, 1: 1.0}  # Adjust these weights if class imbalance persists
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Train Model
history = model.fit(
    X_train, Y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    class_weight=class_weights,
    verbose=1
)

# Evaluate Model
loss, accuracy, precision, recall = model.evaluate(X_test, Y_test)
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype('int32')

# Confusion Matrix and Classification Report
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred_binary))
print("\nClassification Report:")
print(classification_report(Y_test, y_pred_binary))

# Compute ROC-AUC
roc_auc = roc_auc_score(Y_test, y_pred)
print(f"ROC AUC Score: {roc_auc:.4f}")

"""# **NES VS HMS WITH XY**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf
from imblearn.over_sampling import SMOTE

# Load Dataset
file_path = "/content/NES VS HMS(ch)_transposed.csv"
data = pd.read_csv(file_path, low_memory=False)

# Display basic dataset info
print(data.head())
print(data.info())

# Drop non-numeric columns like 'Position' if necessary
data = data.drop(columns=['Position'], errors='ignore')  # Adjust this column name if needed

# Ensure all columns except the target are numeric
data = data.select_dtypes(include=[np.number])

# Separate features and target
target_column = "Classification"  # Replace with the correct target column
if target_column not in data.columns:
    print("Ensure the target column name matches your dataset.")
    exit()

X = data.drop(columns=[target_column])
Y = data[target_column].astype(int)  # Convert target to integer type

print(f"Class distribution: {np.bincount(Y)}")

# Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle Class Imbalance
# Compute the number of samples in the minority class
minority_class_size = np.bincount(Y_train).min()
k_neighbors = min(5, minority_class_size - 1)  # Ensure k_neighbors <= minority class size - 1
if k_neighbors <= 0:
    print("Not enough samples to perform SMOTE. Skipping resampling.")
else:
    smote = SMOTE(random_state=42, k_neighbors=k_neighbors)
    X_train, Y_train = smote.fit_resample(X_train, Y_train)
    print(f"Class distribution after SMOTE: {np.bincount(Y_train)}")

# Build Model
inputs = tf.keras.Input(shape=(X_train.shape[1],))
x = tf.keras.layers.Dense(units=128, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(units=1, activation='sigmoid')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Compile Model
class_weights = {0: 1.0, 1: 1.0}  # Adjust these weights if class imbalance persists
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Train Model
history = model.fit(
    X_train, Y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    class_weight=class_weights,
    verbose=1
)

# Evaluate Model
loss, accuracy, precision, recall = model.evaluate(X_test, Y_test)
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype('int32')

# Confusion Matrix and Classification Report
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred_binary))
print("\nClassification Report:")
print(classification_report(Y_test, y_pred_binary))

# Compute ROC-AUC
if len(np.unique(Y_test)) > 1:  # Ensure ROC-AUC can be calculated
    roc_auc = roc_auc_score(Y_test, y_pred)
    print(f"ROC AUC Score: {roc_auc:.4f}")
else:
    print("ROC AUC Score: Cannot be computed due to single class in Y_test.")

"""# **NES VS HMS WITHOUT XY**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf
from imblearn.over_sampling import SMOTE

# Load Dataset
file_path = "/content/NES VS HMS(wxy)_transposed.csv"
data = pd.read_csv(file_path, low_memory=False)

# Display basic dataset info
print(data.head())
print(data.info())

# Drop non-numeric columns like 'Position' if necessary
data = data.drop(columns=['Position'], errors='ignore')  # Adjust this column name if needed

# Ensure all columns except the target are numeric
data = data.select_dtypes(include=[np.number])

# Separate features and target
target_column = "Classification"  # Replace with the correct target column
if target_column not in data.columns:
    print("Ensure the target column name matches your dataset.")
    exit()

X = data.drop(columns=[target_column])
Y = data[target_column].astype(int)  # Convert target to integer type

print(f"Class distribution: {np.bincount(Y)}")

# Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle Class Imbalance
# Compute the number of samples in the minority class
minority_class_size = np.bincount(Y_train).min()
k_neighbors = min(5, minority_class_size - 1)  # Ensure k_neighbors <= minority class size - 1
if k_neighbors <= 0:
    print("Not enough samples to perform SMOTE. Skipping resampling.")
else:
    smote = SMOTE(random_state=42, k_neighbors=k_neighbors)
    X_train, Y_train = smote.fit_resample(X_train, Y_train)
    print(f"Class distribution after SMOTE: {np.bincount(Y_train)}")

# Build Model
inputs = tf.keras.Input(shape=(X_train.shape[1],))
x = tf.keras.layers.Dense(units=128, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(units=1, activation='sigmoid')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Compile Model
class_weights = {0: 1.0, 1: 1.0}  # Adjust these weights if class imbalance persists
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Train Model
history = model.fit(
    X_train, Y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    class_weight=class_weights,
    verbose=1
)

# Evaluate Model
loss, accuracy, precision, recall = model.evaluate(X_test, Y_test)
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype('int32')

# Confusion Matrix and Classification Report
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred_binary))
print("\nClassification Report:")
print(classification_report(Y_test, y_pred_binary))

# Compute ROC-AUC
if len(np.unique(Y_test)) > 1:  # Ensure ROC-AUC can be calculated
    roc_auc = roc_auc_score(Y_test, y_pred)
    print(f"ROC AUC Score: {roc_auc:.4f}")
else:
    print("ROC AUC Score: Cannot be computed due to single class in Y_test.")

"""# **NES VS WED WITH XY**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf
from imblearn.over_sampling import SMOTE

# Load Dataset
file_path = "/content/NES_VS_WED(ch)_transposed.csv"
data = pd.read_csv(file_path, low_memory=False)

# Display basic dataset info
print(data.head())
print(data.info())

# Drop non-numeric columns like 'Position' if necessary
data = data.drop(columns=['Position'], errors='ignore')  # Adjust this column name if needed

# Ensure all columns except the target are numeric
data = data.select_dtypes(include=[np.number])

# Separate features and target
target_column = "Classification"  # Replace with the correct target column
if target_column not in data.columns:
    print("Ensure the target column name matches your dataset.")
    exit()

X = data.drop(columns=[target_column])
Y = data[target_column].astype(int)  # Convert target to integer type

print(f"Class distribution: {np.bincount(Y)}")

# Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle Class Imbalance
# Compute the number of samples in the minority class
minority_class_size = np.bincount(Y_train).min()
k_neighbors = min(5, minority_class_size - 1)  # Ensure k_neighbors <= minority class size - 1
if k_neighbors <= 0:
    print("Not enough samples to perform SMOTE. Skipping resampling.")
else:
    smote = SMOTE(random_state=42, k_neighbors=k_neighbors)
    X_train, Y_train = smote.fit_resample(X_train, Y_train)
    print(f"Class distribution after SMOTE: {np.bincount(Y_train)}")

# Build Model
inputs = tf.keras.Input(shape=(X_train.shape[1],))
x = tf.keras.layers.Dense(units=128, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(units=1, activation='sigmoid')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Compile Model
class_weights = {0: 1.0, 1: 1.0}  # Adjust these weights if class imbalance persists
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Train Model
history = model.fit(
    X_train, Y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    class_weight=class_weights,
    verbose=1
)

# Evaluate Model
loss, accuracy, precision, recall = model.evaluate(X_test, Y_test)
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype('int32')

# Confusion Matrix and Classification Report
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred_binary))
print("\nClassification Report:")
print(classification_report(Y_test, y_pred_binary))

# Compute ROC-AUC
if len(np.unique(Y_test)) > 1:  # Ensure ROC-AUC can be calculated
    roc_auc = roc_auc_score(Y_test, y_pred)
    print(f"ROC AUC Score: {roc_auc:.4f}")
else:
    print("ROC AUC Score: Cannot be computed due to single class in Y_test.")

"""# **NES VS WED WITHOUT XY**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf
from imblearn.over_sampling import SMOTE

# Load Dataset
file_path = "/content/NES_VS_WED(wxy)_transposed.csv"
data = pd.read_csv(file_path, low_memory=False)

# Display basic dataset info
print(data.head())
print(data.info())

# Drop non-numeric columns like 'Position' if necessary
data = data.drop(columns=['Position'], errors='ignore')  # Adjust this column name if needed

# Ensure all columns except the target are numeric
data = data.select_dtypes(include=[np.number])

# Separate features and target
target_column = "Classification"  # Replace with the correct target column
if target_column not in data.columns:
    print("Ensure the target column name matches your dataset.")
    exit()

X = data.drop(columns=[target_column])
Y = data[target_column].astype(int)  # Convert target to integer type

print(f"Class distribution: {np.bincount(Y)}")

# Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle Class Imbalance
# Compute the number of samples in the minority class
minority_class_size = np.bincount(Y_train).min()
k_neighbors = min(5, minority_class_size - 1)  # Ensure k_neighbors <= minority class size - 1
if k_neighbors <= 0:
    print("Not enough samples to perform SMOTE. Skipping resampling.")
else:
    smote = SMOTE(random_state=42, k_neighbors=k_neighbors)
    X_train, Y_train = smote.fit_resample(X_train, Y_train)
    print(f"Class distribution after SMOTE: {np.bincount(Y_train)}")

# Build Model
inputs = tf.keras.Input(shape=(X_train.shape[1],))
x = tf.keras.layers.Dense(units=128, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(units=1, activation='sigmoid')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Compile Model
class_weights = {0: 1.0, 1: 1.0}  # Adjust these weights if class imbalance persists
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Train Model
history = model.fit(
    X_train, Y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    class_weight=class_weights,
    verbose=1
)

# Evaluate Model
loss, accuracy, precision, recall = model.evaluate(X_test, Y_test)
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype('int32')

# Confusion Matrix and Classification Report
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred_binary))
print("\nClassification Report:")
print(classification_report(Y_test, y_pred_binary))

# Compute ROC-AUC
if len(np.unique(Y_test)) > 1:  # Ensure ROC-AUC can be calculated
    roc_auc = roc_auc_score(Y_test, y_pred)
    print(f"ROC AUC Score: {roc_auc:.4f}")
else:
    print("ROC AUC Score: Cannot be computed due to single class in Y_test.")

"""# **NES VS WED VS HMS WITH XY**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf
from imblearn.over_sampling import SMOTE

# Load Dataset
file_path = "/content/NES_VS_HMS_VS_WED(ch)_transposed.csv"
data = pd.read_csv(file_path, low_memory=False)

# Display basic dataset info
print(data.head())
print(data.info())

# Drop non-numeric columns like 'Position' if necessary
data = data.drop(columns=['Position'], errors='ignore')  # Adjust this column name if needed

# Ensure all columns except the target are numeric
data = data.select_dtypes(include=[np.number])

# Separate features and target
target_column = "Classification"  # Replace with the correct target column
if target_column not in data.columns:
    print("Ensure the target column name matches your dataset.")
    exit()

X = data.drop(columns=[target_column])
Y = data[target_column].astype(int)  # Convert target to integer type

print(f"Class distribution: {np.bincount(Y)}")

# Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle Class Imbalance
smote = SMOTE(random_state=42)
X_train, Y_train = smote.fit_resample(X_train, Y_train)
print(f"Class distribution after SMOTE: {np.bincount(Y_train)}")

# Convert target to one-hot encoding for 3 classes
Y_train_one_hot = tf.keras.utils.to_categorical(Y_train, num_classes=3)
Y_test_one_hot = tf.keras.utils.to_categorical(Y_test, num_classes=3)

# Build Model
inputs = tf.keras.Input(shape=(X_train.shape[1],))
x = tf.keras.layers.Dense(units=128, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(units=3, activation='softmax')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Compile Model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(),
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Train Model
history = model.fit(
    X_train, Y_train_one_hot,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

# Evaluate Model
loss, accuracy, precision, recall = model.evaluate(X_test, Y_test_one_hot)
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Confusion Matrix and Classification Report
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred_classes))
print("\nClassification Report:")
print(classification_report(Y_test, y_pred_classes))

# Compute ROC-AUC (for multiclass)
if len(np.unique(Y_test)) > 1:  # Ensure ROC-AUC can be calculated
    roc_auc = roc_auc_score(Y_test_one_hot, y_pred, multi_class='ovr')
    print(f"ROC AUC Score: {roc_auc:.4f}")
else:
    print("ROC AUC Score: Cannot be computed due to single class in Y_test.")

"""# **NES VS HMS VS WED WITHOUT XY**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf
from imblearn.over_sampling import SMOTE

# Load Dataset
file_path = "/content/NES_VS_HMS_VS_WED(wxy)_transposed.csv"
data = pd.read_csv(file_path, low_memory=False)

# Display basic dataset info
print(data.head())
print(data.info())

# Drop non-numeric columns like 'Position' if necessary
data = data.drop(columns=['Position'], errors='ignore')  # Adjust this column name if needed

# Ensure all columns except the target are numeric
data = data.select_dtypes(include=[np.number])

# Separate features and target
target_column = "Classification"  # Replace with the correct target column
if target_column not in data.columns:
    print("Ensure the target column name matches your dataset.")
    exit()

X = data.drop(columns=[target_column])
Y = data[target_column].astype(int)  # Convert target to integer type

print(f"Class distribution: {np.bincount(Y)}")

# Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle Class Imbalance
smote = SMOTE(random_state=42)
X_train, Y_train = smote.fit_resample(X_train, Y_train)
print(f"Class distribution after SMOTE: {np.bincount(Y_train)}")

# Convert target to one-hot encoding for 3 classes
Y_train_one_hot = tf.keras.utils.to_categorical(Y_train, num_classes=3)
Y_test_one_hot = tf.keras.utils.to_categorical(Y_test, num_classes=3)

# Build Model
inputs = tf.keras.Input(shape=(X_train.shape[1],))
x = tf.keras.layers.Dense(units=128, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(units=3, activation='softmax')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Compile Model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(),
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Train Model
history = model.fit(
    X_train, Y_train_one_hot,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

# Evaluate Model
loss, accuracy, precision, recall = model.evaluate(X_test, Y_test_one_hot)
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Confusion Matrix and Classification Report
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred_classes))
print("\nClassification Report:")
print(classification_report(Y_test, y_pred_classes))

# Compute ROC-AUC (for multiclass)
if len(np.unique(Y_test)) > 1:  # Ensure ROC-AUC can be calculated
    roc_auc = roc_auc_score(Y_test_one_hot, y_pred, multi_class='ovr')
    print(f"ROC AUC Score: {roc_auc:.4f}")
else:
    print("ROC AUC Score: Cannot be computed due to single class in Y_test.")

"""# **SKIN VS MUSCLE TISSUES WITH XY**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf
from imblearn.over_sampling import SMOTE

# Load Dataset
file_path = "/content/Tissues_VS_Muscle(ch)_transposed.csv"
data = pd.read_csv(file_path, low_memory=False)

# Display basic dataset info
print(data.head())
print(data.info())

# Drop non-numeric columns like 'Position' if necessary
data = data.drop(columns=['Position'], errors='ignore')  # Adjust this column name if necessary
data = data.select_dtypes(include=[np.number])  # Keep only numeric columns

# Separate features and target
target_column = "Classification"
if target_column not in data.columns:
    print("Ensure the target column name matches your dataset.")
    exit()

X = data.drop(columns=[target_column])
Y = data[target_column].astype(int)

print(f"Class distribution: {np.bincount(Y)}")

# Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42, stratify=Y
)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle Class Imbalance
minority_class_size = np.bincount(Y_train).min()
k_neighbors = min(5, minority_class_size - 1)  # Dynamically adjust k_neighbors

if minority_class_size > 1 and k_neighbors > 0:
    smote = SMOTE(random_state=42, k_neighbors=k_neighbors)
    X_train, Y_train = smote.fit_resample(X_train, Y_train)
    print(f"Class distribution after SMOTE: {np.bincount(Y_train)}")
else:
    print("Not enough minority samples to apply SMOTE. Proceeding without resampling.")

# Build Model
inputs = tf.keras.Input(shape=(X_train.shape[1],))
x = tf.keras.layers.Dense(units=128, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(units=1, activation='sigmoid')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Compile Model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Train Model
history = model.fit(
    X_train, Y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

# Evaluate Model
loss, accuracy, precision, recall = model.evaluate(X_test, Y_test)
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype('int32')

# Confusion Matrix and Classification Report
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred_binary))
print("\nClassification Report:")
print(classification_report(Y_test, y_pred_binary))

# Compute ROC-AUC
if len(np.unique(Y_test)) > 1:
    roc_auc = roc_auc_score(Y_test, y_pred)
    print(f"ROC AUC Score: {roc_auc:.4f}")
else:
    print("ROC AUC Score: Cannot be computed due to a single class in Y_test.")

"""# **SKIN VS MUSCLE TISSUES WITH XY**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf
from imblearn.over_sampling import SMOTE

# Load Dataset
file_path = "/content/Tissues_VS_Muscle(wxy)_transposed.csv"
data = pd.read_csv(file_path, low_memory=False)

# Display basic dataset info
print(data.head())
print(data.info())

# Drop non-numeric columns like 'Position' if necessary
data = data.drop(columns=['Position'], errors='ignore')  # Adjust this column name if necessary
data = data.select_dtypes(include=[np.number])  # Keep only numeric columns

# Separate features and target
target_column = "Classification"
if target_column not in data.columns:
    print("Ensure the target column name matches your dataset.")
    exit()

X = data.drop(columns=[target_column])
Y = data[target_column].astype(int)

print(f"Class distribution: {np.bincount(Y)}")

# Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42, stratify=Y
)

# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle Class Imbalance
minority_class_size = np.bincount(Y_train).min()
k_neighbors = min(5, minority_class_size - 1)  # Dynamically adjust k_neighbors

if minority_class_size > 1 and k_neighbors > 0:
    smote = SMOTE(random_state=42, k_neighbors=k_neighbors)
    X_train, Y_train = smote.fit_resample(X_train, Y_train)
    print(f"Class distribution after SMOTE: {np.bincount(Y_train)}")
else:
    print("Not enough minority samples to apply SMOTE. Proceeding without resampling.")

# Build Model
inputs = tf.keras.Input(shape=(X_train.shape[1],))
x = tf.keras.layers.Dense(units=128, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(units=1, activation='sigmoid')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Compile Model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

# Train Model
history = model.fit(
    X_train, Y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

# Evaluate Model
loss, accuracy, precision, recall = model.evaluate(X_test, Y_test)
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype('int32')

# Confusion Matrix and Classification Report
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred_binary))
print("\nClassification Report:")
print(classification_report(Y_test, y_pred_binary))

# Compute ROC-AUC
if len(np.unique(Y_test)) > 1:
    roc_auc = roc_auc_score(Y_test, y_pred)
    print(f"ROC AUC Score: {roc_auc:.4f}")
else:
    print("ROC AUC Score: Cannot be computed due to a single class in Y_test.")

import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

# Combine train and test sets
X_full = np.vstack((X_train, X_test))
Y_full = np.hstack((Y_train, Y_test))

# Standardize the dataset before PCA
scaler = StandardScaler()
X_full_scaled = scaler.fit_transform(X_full)

# Perform PCA with whitening for better compactness
pca = PCA(n_components=2, whiten=True)
X_pca_full = pca.fit_transform(X_full_scaled)

# Train an SVM classifier on PCA-transformed data
clf = SVC(kernel='linear', C=1)
clf.fit(X_pca_full, Y_full)

# Create a mesh grid for decision boundary
x_min, x_max = X_pca_full[:, 0].min() - 1, X_pca_full[:, 0].max() + 1  # Keeping points closer
y_min, y_max = X_pca_full[:, 1].min() - 1, X_pca_full[:, 1].max() + 1
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 200), np.linspace(y_min, y_max, 200))
Z = clf.decision_function(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

# Plot decision boundary with a white background
plt.figure(figsize=(8, 6), facecolor='white')
plt.contour(xx, yy, Z, levels=[0], colors='green', linewidths=2)  # Green decision boundary

# Scatter plot with '+' markers for skin and muscle, reducing spread for closeness
for label, color, name in zip([0, 1], ['blue', 'red'], ['Skin 0', 'Muscle 1']):
    plt.scatter(X_pca_full[Y_full == label, 0], X_pca_full[Y_full == label, 1],
                color=color, label=name, alpha=0.9, marker='+', s=30)  # Reduce marker size for compactness

plt.xlim(x_min, x_max)  # Ensuring all points are inside the plot
plt.ylim(y_min, y_max)
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.legend()
plt.grid(False)  # Remove grid for a clean background
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Combine train and test sets
X_full = np.vstack((X_train, X_test))
Y_full = np.hstack((Y_train, Y_test))

# Perform PCA
pca = PCA(n_components=2)
X_pca_full = pca.fit_transform(X_full)

# Scatter plot for PCA visualization
plt.figure(figsize=(8, 6))
for label, color, name in zip([0, 1], ['blue', 'red'], ['Skin', 'Muscle']):
    plt.scatter(X_pca_full[Y_full == label, 0], X_pca_full[Y_full == label, 1],
                color=color, label=name, alpha=0.7)

plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("PCA of Full Dataset (Skin vs Muscle)")
plt.legend()
plt.show()